Bug(cli): code.tar.gz file remains after error occurs
appwrite/sdk-for-cli pull request #99
Opened 2023-10-09 07:51 UTC by Vaibhav91one

## What does this PR do?

- This PR mainly implements a Try catch and finally block to the functionCreatetDeployment.
- As if anything happens in between the finally block will always execute and will remove the remaining file.

## Test Plan

N/A

## Related PRs and Issues

N/A

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-10-31 22:28 UTC, stnguyen90 requested changes

2023-10-31 22:28 UTC, stnguyen90 commented on lib/commands/functions.js
> +    try{
1. Let's not have such a big try/catch
2. This repo is read-only and the change should be done with the [sdk-generator](https://github.com/appwrite/sdk-generator) repo.

2023-10-31 22:30 UTC, stnguyen90 commented
I'm going to add the hacktoberfest-accepted label just so you get credit, but we'll probably close this PR since we need the change in the SDK generator repo.

2024-04-08 20:17 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-05-20 22:34 UTC, closed without merging

2024-05-20 22:35 UTC, stnguyen90 commented
closing as change needs to be done in sdk-generator repo.